[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
mdbook = "0.4.40"
pulldown-cmark = "0.11.0"
semver = "1.0.23"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.121"
