[book]
authors = ["grantkee", "telcoin association"]
language = "en"
multilingual = false
src = "src"
title = "telcoin network improvement proposals"
description = "Collection of community-driven proposals to improve Telcoin Network protocol."

[rust]
edition = "2018"

[output.html]
smart-punctuation = true
# hide numbers
no-section-label = true
additional-css = ["theme/css/pagetoc.css"]
additional-js = ["theme/js/pagetoc.js"]
cname = "tnips.telcoin.network"
git-repository-url = "https://github.com/telcoin-association/TNIPs/"

[output.html.playground]
editable = true
line-numbers = true
