[book]
authors = ["grantkee", "telcoin association"]
language = "en"
multilingual = false
src = "src"
title = "telcoin network improvement proposals"
description = "Collection of community-driven proposals to improve Telcoin Network protocol."

[rust]
edition = "2018"

[build]
build-dir = "../build"
create-missing = false
use-default-preprocessors = true

[preprocessor.frontmatter]
command = "cargo run --manifest-path process-frontmatter/Cargo.toml"
renderer = ["html"]

[output.html]
smart-punctuation = true
# hide numbers
no-section-label = true
additional-css = ["theme/css/pagetoc.css", "theme/css/preamble.css"]
additional-js = ["theme/js/pagetoc.js"]
cname = "tnips.telcoin.network"
git-repository-url = "https://github.com/telcoin-association/TNIPs/"

[output.html.playground]
editable = true
line-numbers = true
