name: Continuous Integration

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - edited

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  link-check:
    name: Link Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout TNIP Repository
        uses: actions/checkout@47fbe2df0ad0e27efb67a70beac3555f192b062f

      - name: Link Checker
        uses: gaurav-nelson/github-action-markdown-link-check@d53a906aa6b22b8979d33bc86170567e619495ec
        with:
          config-file: config/mlc_config.json
          use-quiet-mode: no
          use-verbose-mode: yes
          check-modified-files-only: yes

  codespell:
    name: CodeSpell
    runs-on: ubuntu-latest

    steps:
      - name: Checkout EIP Repository
        uses: actions/checkout@47fbe2df0ad0e27efb67a70beac3555f192b062f

      - name: Get Changed Files
        id: changed
        continue-on-error: true
        run: |
          echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
          gh pr diff ${{ github.event.number }} --name-only | sed -e 's|$|,|' | xargs -i echo "{}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run CodeSpell
        uses: codespell-project/actions-codespell@57beb9f38f49d773d641ac555d1565c3b6a59938
        if: steps.changed.outcome == 'success'
        with:
          check_filenames: true
          ignore_words_file: config/.codespell-whitelist
          path: ${{ env.CHANGED_FILES }}
          skip: .git,Gemfile.lock,**/*.png,**/*.gif,**/*.jpg,**/*.svg,.codespell-whitelist,vendor,_site,_config.yml,style.css

  eipw-validator:
    name: EIP Walidator
    runs-on: ubuntu-latest

    steps:
      - name: Checkout EIP Repository
        uses: actions/checkout@47fbe2df0ad0e27efb67a70beac3555f192b062f

      - uses: ethereum/eipw-action@b8de7ea9ad5cb842301e63898afb996c451c18cf
        id: eipw
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          unchecked: 1, 5069, 5757
          options-file: config/eipw.toml

  markdownlint:
    name: Markdown Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout EIP Repository
        uses: actions/checkout@47fbe2df0ad0e27efb67a70beac3555f192b062f

      - name: Get Changed Files
        id: changed
        continue-on-error: true
        run: |
          echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
          gh pr diff ${{ github.event.number }} --name-only | grep -E -x '[^/]+\.md|EIPS/eip-[0-9]+\.md' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        uses: DavidAnson/markdownlint-cli2-action@f5cf187ef11bd3a68a127321b794aa252ff23019
        if: steps.changed.outcome == 'success'
        with:
          command: config
          globs: |
            config/.markdownlint.yaml
            ${{ env.CHANGED_FILES }}
